### ISSUE TITLE
Checkout Error

### ISSUE THREAD

**Issue by kennedyi** [lvegerano/label-required-approvals#3]
I tried to run this but it produced a checkout error " File .github/team-approvers.yml could not be found in your project's workspace. You may need the actions/checkout action to clone the repository first."

I tried adding the step to the workflow, but that did not resolve?

Also, the readme for the label-approvers.yml file needs to be updated as the format is incorrect.

**Comment by lvegerano** [comment]
Thanks for the report. Can you provide the workflow config file?

**Comment by kennedyi** [comment]
See below. You may have to redo the indentation as it is not formatting correctly.

`name: label-required-approvals

on:
  pull_request:
    types:
      - opened
      - reopened
      - labled
      - unlabeled

jobs:
  required-approvals:
    runs-on: ubuntu-latest
    steps:
      - uses: lvegerano/label-required-approvals@v1.0.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"`

**Comment by kennedyi** [comment]
Any updates on this?

**Comment by lvegerano** [comment]
```
name: Required Label Reviews
on:
  pull_request_review:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]
jobs:
  required-label-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lvegerano/label-required-approvals@v1.0.0
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          status: 'Label Required Reviews'
```

This is a setup I'm running in a private repo. One thing I ran into was not being able to use the GITHUB_TOKEN because of other workflows. Instead, I created a personal access token.

Have you tried a PAT instead of the GITHUB_TOKEN? [Here](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow) there is some info about using GITHUB_TOKEN in workflows.

Is there any output as far as errors go?
